# Generated by Django 3.2.2 on 2021-10-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='趣味'),
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明文'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介文'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='genre',
            field=models.CharField(choices=[('0', 'フロントエンド'), ('1', 'バックエンド'), ('2', 'デプロイ'), ('3', '電子回路'), ('4', 'その他')], default='', max_length=1, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
